export type VersionNote = {
  version: string
  date: string
  title: string
  features: string[]
  bugFixes: string[]
  breaking: string[]
}

export const VERSION_NOTES: VersionNote[] = [
  {
    version: '5.2.1',
    date: '2026-01-09',
    title: 'CRITICAL FIX: Recurring Income Calculations',
    features: [
      'NEW: "Earned This Month" shows actual income received so far',
      'NEW: "Expected Remaining" shows income still to be received this month',
      'IMPROVED: Dashboard "Income This Month" now counts actual occurrences',
    ],
    bugFixes: [
      'CRITICAL FIX: Bi-weekly income now properly counts 3 paychecks in months like January',
      'FIXED: Recurring income calculations now count actual pay dates, not estimates',
      'FIXED: Weekly/bi-weekly/monthly income accurately reflects real occurrences',
      'FIXED: Income page now shows accurate totals for recurring payments',
    ],
    breaking: [],
  },
  {
    version: '5.2.0',
    date: '2026-01-09',
    title: 'Improved Transaction Filters - Search Button',
    features: [
      'NEW: Search button - filters only apply when you click "Search"',
      'NEW: Month dropdown with all 12 months',
      'NEW: Year dropdown (±5 years from current)',
      'NEW: Text search box to find transactions by description',
      'NEW: Clear Filters button to reset all at once',
      'IMPROVED: No more page reloading while typing',
      'IMPROVED: Cleaner, more responsive filter experience',
    ],
    bugFixes: [],
    breaking: [],
  },
  {
    version: '5.1.5',
    date: '2026-01-09',
    title: 'CRITICAL FIX: Recurring Expenses Now Generate Actual Purchases',
    features: [],
    bugFixes: [
      'CRITICAL FIX: Recurring expenses now properly convert to actual purchases when their date arrives',
      'FIXED: Past projected purchases are automatically converted to actual purchases',
      'FIXED: Recurring expenses now appear in transaction history after their date',
      'FIXED: Recurring expenses now count towards spending totals',
      'FIXED: NEW recurring expenses backfill past dates in current month as actual purchases',
      'ADDED: Cleanup function runs on app load to catch any missed conversions',
    ],
    breaking: [],
  },
  {
    version: '5.1.4',
    date: '2026-01-09',
    title: 'PWA Support - Add to Home Screen',
    features: [
      'Sleek minimalist app icon with blue-purple gradient',
      'Add to Home Screen support for iOS and Android',
      'PWA (Progressive Web App) manifest',
      'Standalone app mode - no browser UI when launched from home screen',
      'Custom splash screen and theme colors',
      'Icon generation script for easy customization',
    ],
    bugFixes: [
      'FIXED: Transactions page chart now uses correct category colors',
      'FIXED: Pie chart labels now positioned outside to prevent overlap',
      'FIXED: Small slices (<5%) hide labels to reduce clutter',
      'IMPROVED: Tags now inherit colors from their categories',
      'IMPROVED: Label lines connect slices to text for clarity',
    ],
    breaking: [],
  },
  {
    version: '5.1.3',
    date: '2026-01-09',
    title: 'Beta Charts & Dashboard Improvements',
    features: [
      'BETA: Spending analysis pie charts on History and Transactions pages',
      'Toggle between category view and tags view in charts',
      'Items without tags show under their category name',
      'Dashboard budget card now shows "Budget Remaining" as main number',
      'Changed "x remaining" to "x spent" for clarity',
      'Social Security and Medicare already included in salary deductions',
    ],
    bugFixes: [
      'IMPROVED: Budget card now highlights remaining budget instead of spent',
      'IMPROVED: Chart colors match category colors in category view',
      'IMPROVED: Charts only show actual spending (no projected purchases)',
    ],
    breaking: [],
  },
  {
    version: '5.1.2',
    date: '2026-01-09',
    title: 'Aggressive Mobile Optimization + Health Check',
    features: [
      'Health check endpoint for keeping Render awake (/api/health)',
    ],
    bugFixes: [
      'FIXED: History page now properly fits mobile screens without zoom',
      'FIXED: Transactions page mobile optimization',
      'FIXED: Income page mobile optimization',
      'FIXED: Reduced padding from 16px to 12px on mobile',
      'FIXED: Text sizes reduced - titles from 24px to 20px on mobile',
      'FIXED: Category items use 12px text on mobile',
      'FIXED: Progress bars thinner on mobile (6px vs 10px)',
      'FIXED: Table padding reduced to 8px on mobile',
      'FIXED: Date format shortened to "MMM d" on mobile tables',
      'IMPROVED: All spacing optimized for small screens',
      'IMPROVED: Desktop view completely unchanged',
    ],
    breaking: [],
  },
  {
    version: '5.1.1',
    date: '2026-01-08',
    title: 'Critical Fixes & New Features',
    features: [
      'Keep me signed in - Option to stay logged in across sessions',
      'Forgot password - Password reset functionality via email',
      'Auto-show version notes - Only displayed once after updates',
      'Better mobile viewport - Proper scaling without zoom issues',
    ],
    bugFixes: [
      'FIXED: History page now correctly calculates net worth (debt subtracts from assets)',
      'FIXED: Debt displays in red with negative sign on history page',
      'FIXED: Transactions "Add Purchase" button no longer spans full width on desktop',
      'FIXED: Mobile viewport settings prevent forced zoom-out',
      'IMPROVED: Version notes only show on first login after update',
      'IMPROVED: Session management with keep signed in option',
    ],
    breaking: [],
  },
  {
    version: '5.1',
    date: '2026-01-08',
    title: 'Mobile Optimization & Layout Improvements',
    features: [
      'Comprehensive mobile optimization for History, Transactions, and Income pages',
      'Redesigned page headers - Add buttons now below title/description on Assets, Recurring, Goals, Categories',
      'Full-width buttons on mobile for better touch targets',
      'Responsive text sizes throughout (smaller on mobile, larger on desktop)',
      'Optimized padding and spacing for mobile screens',
      'Categories page now properly labeled everywhere (no more "Settings")',
    ],
    bugFixes: [
      'FIXED: Categories page header now says "Categories" instead of "Settings"',
      'FIXED: Removed duplicate description text on Categories page',
      'IMPROVED: History page cards now responsive (2-col mobile, 3-col desktop)',
      'IMPROVED: Transactions page hides "Add Purchase" button on mobile (use bottom nav)',
      'IMPROVED: Income page cards optimized for mobile viewing',
      'IMPROVED: All page headers now mobile-friendly with responsive text',
    ],
    breaking: [],
  },
  {
    version: '5.0.1',
    date: '2026-01-08',
    title: 'Bug Fix - Removed Mystery "0" Text & Import Fix',
    features: [],
    bugFixes: [
      'FIXED: Removed "0" text appearing below category progress bars',
      'FIXED: Removed overflow-hidden class causing unwanted text nodes',
      'FIXED: Added missing format import from date-fns to recurring page',
      'IMPROVED: Removed all emojis from version notes for more professional appearance',
    ],
    breaking: [],
  },
  {
    version: '5.0.0',
    date: '2026-01-08',
    title: 'Mobile Makeover - Complete Navigation Redesign',
    features: [
      'NEW Mobile Navigation - Completely redesigned bottom nav',
      'History Tab - Now correctly navigates to Monthly History page (not Transactions)',
      'More Menu - NEW! Access all pages from one menu (Transactions, Recurring, Income, Goals, Categories, Sign Out)',
      'Mobile Optimization - Dashboard cards now 2-column grid on mobile',
      'Better Touch Targets - Larger tap areas for mobile users',
      'Responsive Padding - Optimized spacing for small screens',
      'Adaptive Text Sizes - Smaller fonts on mobile, larger on desktop',
    ],
    bugFixes: [
      'FIXED: Mobile "History" tab was going to Transactions instead of History page',
      'FIXED: Goals taking up valuable bottom nav space on mobile',
      'IMPROVED: Dashboard now properly responsive with 2-column card layout on mobile',
      'IMPROVED: Hidden "Add Purchase" button on mobile (use center + button instead)',
    ],
    breaking: [
      'Mobile navigation completely redesigned - users will need to learn new layout',
    ],
  },
  {
    version: '4.4.6',
    date: '2026-01-08',
    title: 'Dashboard Cleanup & UI Improvements',
    features: [
      'Renamed "Settings" to "Categories" with bar chart icon',
      'Cleaner category display without unnecessary styling hacks',
    ],
    bugFixes: [
      'FIXED: Removed mysterious "0" text appearing below categories with no upcoming charges',
      'FIXED: Removed unnecessary fontSize: 0 CSS hack causing display issues',
      'IMPROVED: Removed redundant "Upcoming" card from dashboard summary',
      'IMPROVED: Dashboard now has cleaner 4-card layout matching original design',
    ],
    breaking: [],
  },
  {
    version: '4.4.5',
    date: '2026-01-08',
    title: 'History Page Fix - Past Recurring Charges',
    features: [],
    bugFixes: [
      'FIXED: History page now correctly shows past recurring charges as "Paid" instead of "Upcoming"',
      'FIXED: Past recurring charges now count toward spending totals in history page',
      'FIXED: Category spending calculations in history now include past projected purchases',
      'IMPROVED: History page now uses same logic as Dashboard and Transactions for determining paid vs upcoming',
    ],
    breaking: [],
  },
  {
    version: '4.4.4',
    date: '2026-01-08',
    title: 'Critical: Duplicate Recurring Charge Fix',
    features: [
      'Added dedicated "Upcoming" card to dashboard summary showing projected charges',
      'Added detailed console logging for debugging projected purchase calculations',
      'Dashboard now matches transaction page layout with 5 summary cards',
    ],
    bugFixes: [
      'CRITICAL FIX: Recurring charges no longer duplicate when page refreshes or multiple tabs open',
      'Added database unique constraint to prevent duplicate projected purchases',
      'Sync function now handles race conditions gracefully',
      'IMPROVED: Dashboard now clearly displays total upcoming charges in summary',
      'IMPROVED: Better visibility of projected vs actual spending',
    ],
    breaking: [
      'MIGRATION REQUIRED: Run migration_v4.4.4_unique_projected.sql in Supabase SQL Editor',
    ],
  },
  {
    version: '4.4.3',
    date: '2026-01-08',
    title: 'Duplicate Recurring Purchase Fix',
    features: [],
    bugFixes: [
      'FIXED: Recurring expenses no longer counted twice on dashboard',
      'FIXED: Projected purchases sync now preserves past recurring (prevents re-creation)',
      'FIXED: Only future projected purchases are regenerated on sync',
      'FIXED: Duplicate check now prevents any duplicate purchases for same date+description',
    ],
    breaking: [],
  },
  {
    version: '4.4.2',
    date: '2026-01-08',
    title: 'Critical Recurring Payment Fixes',
    features: [
      'Edit asset modal now displays immediately (no back button needed)',
    ],
    bugFixes: [
      'FIXED: Paid recurring expenses now show correctly on dashboard',
      'FIXED: Subscription totals now accurate (paid vs upcoming properly separated)',
      'FIXED: ReferenceError crash when filtering transactions (parse_local_date hoisting issue)',
      'FIXED: Paid recurring now appears in "Actual Paid" filter on transactions page',
      'FIXED: Dashboard categories now correctly count paid recurring in spent amount',
    ],
    breaking: [],
  },
  {
    version: '4.4.1',
    date: '2026-01-08',
    title: 'Critical Bug Fixes & Asset Editing',
    features: [
      'Edit asset name and type after creation',
      'Color-coded asset cards (blue=retirement, purple=general, green=investments, red=debt)',
      'Soccer goal icon in sidebar navigation',
    ],
    bugFixes: [
      'FIXED: Upcoming filter now correctly excludes past-dated recurring expenses',
      'FIXED: Upcoming total only counts truly future transactions',
      'FIXED: Past recurring expenses no longer counted as "upcoming"',
      'FIXED: Persistent "0" display under budget categories (aggressive fix)',
    ],
    breaking: [],
  },
  {
    version: '4.4.0',
    date: '2026-01-07',
    title: 'Asset Types & Major UX Improvements',
    features: [
      'Asset categorization: Track debt, retirement, investments, and general assets separately',
      'Custom asset types: Create your own categories',
      'Asset summary by category: See your net worth breakdown at a glance',
      'Improved per-month savings calculation using actual days',
      'Better recurring expense handling - past due items no longer show as "upcoming"',
      'Recent transactions now only shows paid items (not future projected)',
    ],
    bugFixes: [
      'Fixed persistent "0" display under budget categories',
      'Fixed upcoming charges showing for past-dated recurring expenses',
      'Fixed dashboard showing future transactions in recent list',
      'Improved date handling across all pages',
    ],
    breaking: [],
  },
  {
    version: '4.3.2',
    date: '2026-01-06',
    title: 'Income/Recurring Dates & History Fixes',
    features: [
      'Start/end dates for income sources',
      'Start/end dates for recurring expenses',
      'Warning when changing income/recurring values',
      'Fixed asset value history ordering',
    ],
    bugFixes: [
      'Fixed major date timezone issue (purchases showing day behind)',
      'Fixed same-day asset value changes ordering',
      'Expired income/recurring now shows at bottom with badge',
    ],
    breaking: [],
  },
  {
    version: '4.3.1',
    date: '2026-01-05',
    title: 'Tag System & UX Improvements',
    features: [
      'Tag autocomplete in transaction edit',
      'Auto-save tags on submit (no Enter needed)',
      '"Upcoming" checkbox for new purchases',
    ],
    bugFixes: [
      'Fixed past recurring showing as "Upcoming"',
      'Fixed date timezone on new purchases',
    ],
    breaking: [],
  },
  {
    version: '4.3.0',
    date: '2026-01-04',
    title: 'Transaction Management & Features',
    features: [
      'Full transaction edit functionality',
      'Transaction delete with confirmation',
      'Yearly recurring with specific month + day selection',
      'Goals auto-sync with linked asset values',
      'Version display in sidebar',
    ],
    bugFixes: [
      'Fixed category "0" display issue',
    ],
    breaking: [],
  },
]

export const CURRENT_VERSION = VERSION_NOTES[0].version
